### ISSUE TITLE
roadmap to TestImages v1.2

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/TestImages.jl#69]
This is of low priority to myself but I'd like to plot what I have in mind for the next minor version of TestImages in case someone wants to pick a task and make a contribution here.

- [x] make artifacts PkgServer friendly and lazy downloads (#67)
- [x] dynamic generation: some images are generated on the fly, e.g., the widely used MRI test image [shepp logan phantom](https://github.com/JuliaImages/Images.jl/issues/899) #77 
- [ ] ~~generic pre-processing and post-processing handlers: some images require pre- and post-processing, e.g., [`mri-stack`](https://github.com/JuliaImages/TestImages.jl/blob/eaa94348df619c65956e8cfb0032ecddb7a29d3a/src/TestImages.jl#L79-L83)~~
- [ ] dataset support: there're some widely used datasets used for benchmark purposes, an example of this is [BSD500](https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/resources.html). Although we could bundle this into the same `testimage` method, it would be better to implement it in a new function `testset` (note the similarity to `Test.@testset`) or `testdataset`. I prefer `testset` because it looks nicer.

All of these should be relatively easy to implement.

Please comment if you have any other ideas

**Comment by johnnychen94** [comment]
I'm really unsure whether we should add datasets to this package because:

1) most datasets are of large size; tracking them using Git is not a very good idea.
2) different projects need different datasets; we definitely can't satisfy all.
